- name: Install NFS packages
  ansible.builtin.dnf:
    name: "nfs-utils"
    state: latest
  become: true
  become_user: root
- name: Make directory to export
  ansible.builtin.file:
    path: /nfs
    state: directory
  become: true
  become_user: root
- name: NFS mount
  ansible.posix.mount:
    boot: true
    state: mounted
    fstype: nfs
    src: "{{groups['mgmtnode'][0]}}:/nfs"
    path: /nfs
    opts: defaults,_netdev
  become: true
  become_user: root
- name: Create home directory sym-link
  ansible.builtin.file:
    src: /nfs/almalinux
    dest: /home/almalinux/nfs
    state: link
  become: true
  become_user: root